version: "3.9"

services:
  web:
    container_name: web_container
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
    - 8000:8000
